services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: always
  #   environment:
  #     DB_DSN: "root:root@tcp(mysql:3306)/restaurant_db?parseTime=true"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      API_URL: http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - mysql