name: Semantic Release

on:
  push:
    branches:
      - main       

jobs:
  release:
    runs-on: ubuntu-latest
    name: Semantic Release
    environment:
      name: main
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
